trigger:
  batch: true
  branches:
    include:
      - 7.0

variables:
  skipComponentGovernanceDetection: true

pool: '1ES-Host-Ubuntu'

jobs:
  - job: VRToolUpdateBaseline_V7
    variables:
      pipelineId: '314'
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml
      - template: download-vr-cli.yml
      - template: .devops/templates/runpublishvrscreenshot.yml
        parameters:
          fluentVersion: v7
          vrTestPackageName: 'vr-tests'
          vrTestPackagePath: 'apps/vr-tests'

      - bash: vr-app run-diff --buildType release --screenshotsDirectory ./screenshots --clientType "FLUENTUI" --locationPrefix 'FluentUI-v7' --locationPostfix 'vrscreenshotv7' --pipelineId $(pipelineId)
        displayName: 'Run Screenshotdiff update baseline'
        env:
          API_TOKEN: $(fabric-public-pipeline-access-PAT)
          GITHUB_API_TOKEN: $(githubRepoStatusPAT)
          STORAGE_CONNECTION_STRING: $(BLOB-CONNECTION-STRING)
          VR_APP_CLIENT_SECRET: $(VR-APPROVAL-CLIENT-SECRET)
          VR_APP_CLIENT_ID: $(VR_APP_CLIENT_ID)
          VR_APP_API_URL: $(VR_APP_API_URL)
